dreamyPatisiel/devdevdev-server

src/main/java/com/dreamypatisiel/devdevdev/global/properties/CorsProperties.java, src/main/java/com/dreamypatisiel/devdevdev/global/security/config/CorsConfig.java, src/main/resources/application-local.yml, src/test/java/com/dreamypatisiel/devdevdev/web/CorsProperties.java, src/test/java/com/dreamypatisiel/devdevdev/web/CorsTest.java, src/test/resources/application-test.yml
- cors.origin 프로퍼티를 String-> List로 변경
- CorsTest 테스트코드에서도 origin list에 대해 모두 테스트할 수 있도록 변경
- 프로퍼티 읽어올 수 있도록 @ConfigurationProperties 클래스 생성
- CorsTest에서 해당 프로퍼티에 접근할 수 있도록 설정 및 @MethodSource, @ParameterizedTest 적용
=> [DP-105] origin String → List로 변경

src/main/java/com/dreamypatisiel/devdevdev/global/config/SwaggerConfig.java
http 프로토콜을 사용하는 Generated Server가 아닌 Swagger 서버를 생성하도록 변경
참고(https://github.com/springdoc/springdoc-openapi/issues/726)
=> [DP-140] Swagger servers url 추가

src/docs/asciidoc/api/pick/pick-modify.adoc, src/docs/asciidoc/api/tech-article/bookmark.adoc, src/docs/asciidoc/api/tech-article/detail.adoc, src/main/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleController.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickControllerDocsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
-  request path id -> techArticleId 형식으로 명시적으로 변경
- 픽피픽 수정 docs에 path param 추가 및 patch import 변경(MockMvcRequestBuilders → RestDocumentationRequestBuilders )
- 그외 오타 수정
=> [DP-174] 요청시 id -> techArticleId 형식으로 명시적으로 변경

src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/CompanyResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PickOptionResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PickUploadImageResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PicksResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/TechArticleResponse.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
* null 응답 필드도 전달하도록 변경
* boolean에 null은 없다! true | false
* 복수형 빈 값은 빈 배열로!!
* Null Object Pattern
* object 만 null 허용
* 의미 있는 null 값이 있는 경우라면 Enum 으로 대체
=> [PRD-183] API Response 변경

src/docs/asciidoc/api/mypage/delete-member.adoc, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/member/AnonymousMemberRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java, src/main/java/com/dreamypatisiel/devdevdev/global/security/oauth2/handler/OAuth2SuccessHandler.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/MypageController.java, src/main/resources/application.yml, src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java
- 회원탈퇴시 해당 member 엔티티의 isDeleted가 true로 업데이트 됩니다.
- @SQLRestriction을 통해 member 엔티티 조회시 isDeleted = false를 디폴트 옵션으로 조회하도록 합니다.
- 대부분의 엔티티가 is_deleted = false인 경우, 인덱스를 설정하면 오히려 효율성이 떨어질 수 있기 때문에 인덱스를 추가하진 않았습니다.
- @SQLDelete를 통해, 추후 member 엔티티의 Delete 쿼리가 호출되더라도 소프트삭제로 변경되도록 하였습니다.
```java
@SQLDelete(sql = "UPDATE member SET is_deleted = true, deletedAt = NOW() WHERE id = ?")
@SQLRestriction("is_deleted = false")
public class Member extends BasicTime {
...
}
```
=> [DP-177] 회원탈퇴 API

src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java, src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/model/JwtCookieConstant.java, src/main/java/com/dreamypatisiel/devdevdev/global/security/oauth2/handler/OAuth2SuccessHandler.java, src/main/java/com/dreamypatisiel/devdevdev/global/utils/CookieUtils.java, src/test/java/com/dreamypatisiel/devdevdev/global/security/oauth2/handler/OAuth2SuccessHandlerTest.java, src/test/java/com/dreamypatisiel/devdevdev/global/utils/CookieUtilsTest.java
- OAuth2 로그인 성공시 쿠키에 `DEVDEVDEV_MEMBER_EMAIL`, `DEVDEVDEV_MEMBER_NICKNAME` 을 담아 응답합니다.
- 각 회원 정보 쿠키의 유효기간은 AccessToken과 동일합니다.
- 쿠키는 콤마(,) 세미콜론(:) 공백문자( ) 를 제외하고는 모두 ASCII 코드로 구성되기 때문에 한글 사용이 불가능하므로, 닉네임은 UTF8 인코딩 과정을 거친 후 쿠키에 저장됩니다.
=> [DP-193] 로그인시 회원 정보(이메일, 닉네임) 쿠키에 담아 응답

src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickOption.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickRepositoryImpl.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechArticleRepositoryImpl.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PickDetailOptionResponse.java, src/test/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/PickOptionContentsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
- 픽픽픽 메인 조회시 요청 size의 +1의 크기로 응답 보내던 것 수정(limit 값 수정)
```java
// before
long limit = pageable.getPageSize() * TWO + ONE;
// after
long limit = pageable.getPageSize() * TWO;
```
- 픽픽픽/기술블로그 조회시 last 로직 에러 수정
```java
// before
private boolean hasNextPage(List<Pick> contents, int pageSize) {
return contents.size() > pageSize;
// after
private boolean hasNextPage(List<Pick> contents, int pageSize) {
return contents.size() >= pageSize; // 등호 추가
}
```
- PickOptionContents가 null일 경우 "" 빈문자열 응답하도록 수정
```java
public String getContentsAsString() {
String pickOptionContents = contents.getPickOptionContents();
if (pickOptionContents == null) {
return "";
}
return pickOptionContents;
}
```
=> [DP-210] 픽픽픽/기술블로그 페이지네이션 에러 수정 & 픽픽픽 옵션 내용 null 가능하도록 수정

src/docs/asciidoc/api/tech-article/main.adoc, src/main/java/com/dreamypatisiel/devdevdev/domain/exception/TechArticleExceptionMessage.java, src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleService.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/exception/ApiControllerAdvice.java, src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
- 검색 불가 특수문자 ! ^ ( ) - + / [ ] { } :
- 검색 가능 특수문자 @ = # $ % & * _ = < > , . ? ;  '
```java
{
"resultType" : "FAIL",
"message" : "검색어에 특수문자는 포함할 수 없어요",
"errorCode" : 400
}
```
=> [DP-219] 검색 키워드에 특수문자가 있을 경우 예외 발생

src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleService.java, src/main/java/com/dreamypatisiel/devdevdev/elastic/data/domain/ElasticSlice.java, src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleService.java, src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleServiceTest.java
- ElasticTechArticleService의 getTechArticles(..) 응답타입을 `List<ElasticResponse<ElasticTechArticle>>` → `SearchHits<ElasticTechArticle>`으로 변경하였습니다.
- ElasticTechArticleService 내부에서 가공하여 리턴하지 않고, Guest/MemberTechArticleService에서 SearchHits 전체를 응답받은 후 이 응답값을 가공하여 사용합니다. (리팩토링 이전 버전과 동일)
Before:
```java
// 엘라스틱서치 기술블로그 조회
List<ElasticResponse<ElasticTechArticle>> elasticTechArticles = elasticTechArticleService.getTechArticles(
pageable, elasticId, techArticleSort, keyword, companyId, score);
```
After:
```java
// 엘라스틱서치 기술블로그 조회
SearchHits<ElasticTechArticle> elasticTechArticleSearchHits = elasticTechArticleService.getTechArticles(
pageable, elasticId, techArticleSort, keyword, companyId, score);
List<ElasticResponse<ElasticTechArticle>> elasticTechArticles = …
```
=> [DP-227] 기술블로그 조회 총 개수 이슈 수정

src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/member/MemberRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/util/PickResponseUtils.java, src/main/java/com/dreamypatisiel/devdevdev/global/common/MemberProvider.java, src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/service/JwtMemberService.java, src/main/java/com/dreamypatisiel/devdevdev/global/security/oauth2/service/OAuth2MemberService.java, src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticsearchSupportTest.java, src/test/java/com/dreamypatisiel/devdevdev/global/security/jwt/service/JwtMemberServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/global/security/oauth2/handler/OAuth2SuccessHandlerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/TokenControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TokenControllerDocsTest.java
- Member 엔티티의 @SQLRestriction를 제거했습니다.
```java
@SQLDelete(sql = "UPDATE member SET is_deleted = true, deletedAt = NOW() WHERE id = ?")
//@SQLRestriction("is_deleted = false")
```
- MemberProvider에서 Authentication으로 회원을 조회할 때 탈퇴회원을 확인하는 구문을 추가했습니다.
```java
return memberRepository.findMemberByEmailAndSocialType(new Email(email), socialType)
.orElseThrow(() -> new MemberException(MemberException.INVALID_MEMBER_NOT_FOUND_MESSAGE));
=>
return memberRepository.findMemberByEmailAndSocialTypeAndIsDeletedIsFalse(new Email(email), socialType)
.orElseThrow(() -> new MemberException(MemberException.INVALID_MEMBER_NOT_FOUND_MESSAGE));
```
- 내가 작성한 픽픽픽에서 `isPicked`가 누락되는 부분을 수정했습니다. (cc. @ssosee)
=> [DP-244] 내작픽 수정 & 탈퇴회원 조회 관련 수정

src/docs/asciidoc/api/mypage/exit-member.adoc, src/main/java/com/dreamypatisiel/devdevdev/domain/exception/MemberExceptionMessage.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/survey/SurveyAnswerRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/survey/custom/SurveyAnswerRepositoryCustom.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/survey/custom/SurveyAnswerRepositoryImpl.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java, src/main/java/com/dreamypatisiel/devdevdev/exception/MemberException.java, src/main/java/com/dreamypatisiel/devdevdev/exception/SurveyException.java, src/main/java/com/dreamypatisiel/devdevdev/global/common/MemberProvider.java, src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/service/JwtMemberService.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/global/common/MemberProviderTest.java, src/test/java/com/dreamypatisiel/devdevdev/global/security/jwt/service/JwtMemberServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/global/security/oauth2/handler/OAuth2SuccessHandlerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
- 탈퇴를 요청하는 회원이 모든 회원탈퇴 서베이 질문에 대해 답변을 완료했는지 확인합니다.
- 만약 서베이를 완료하지 않은 회원이 탈퇴를 요청할 경우 예외가 발생합니다.
```java
public boolean hasAnsweredAllQuestions(Member member, List<Long> ids) {
// 주어진 질문 ID 리스트에 대해 해당 멤버의 답변 여부를 체크
long answeredQuestionCount = query
.select(surveyAnswer.surveyQuestion.id)
.from(surveyAnswer)
.where(surveyAnswer.member.eq(member)
.and(surveyAnswer.surveyQuestion.id.in(ids)))
.groupBy(surveyAnswer.surveyQuestion.id)
.fetchCount();
// 답변이 있는 질문의 수와 주어진 질문 ID 리스트의 크기가 동일하면 true 반환
return answeredQuestionCount == ids.size();
}
```
=> [DP-228] 회원탈퇴시 서베이 완료 여부 확인

src/main/java/com/dreamypatisiel/devdevdev/LocalInitData.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Company.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/CompanyResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/TechArticleMainResponse.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/response/TechArticleMainResponseTest.java, src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticsearchSupportTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
- 이미지는 S3에 업로드되어있어요.
- 이미지 Url 이므로 타입은 String으로 지정했습니다.
- Company 응답에 회사로고 이미지가 포함됩니다.
- 만약 기술블로그의 썸네일 이미지가 없다면 회사로고 이미지가 해당 값으로 들어갑니다.(프론트에서 추가 공수가 들지 않도록 하기 위함)
```
"content" : [ {
"id" : 1,
"thumbnailUrl" : "http://companyLogo.png", // 만약 기술블로그의 썸네일 이미지가 없다면 회사로고 이미지가 해당 값으로 들어갑니다.
"techArticleUrl" : "http://example.com/9",
...
"company" : {
"id" : 2,
"name" : "꿈빛 파티시엘",
"careerUrl" : "https://example.com",
"thumbnailImageUrl" : "https://companyLogo.png" // Company 응답에 회사로고 이미지가 포함됩니다.
}
}]
```
=> [DP-255] 썸네일 이미지 없을 시 회사 로고 이미지 전달

src/main/java/com/dreamypatisiel/devdevdev/domain/entity/AnonymousMember.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Pick.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/util/PickResponseUtils.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/util/TechArticleResponseUtils.java
* 픽픽픽 메인 API 에서 투표를 했는데, 투표를 안한 것으로 응답하는 현상 발견(사진참고)
* PickResponseUtils 수정
* object.equals() 에서 object.id.equals() 로 변경
=> [DP-328] 픽픽픽 투표 응답 버그 수정

src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/document/ElasticKeyword.java, src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticKeywordService.java, src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticKeywordServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/KeywordControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/KeywordControllerDocsTest.java
- ElasticKeyword 도큐먼트 속성 변경
- 인덱스 설정 변경에 따른 필드 type 변경(completion → text)
- 필드명 변경(words → keyword)
- 검색 쿼리 변경
- multi_match 쿼리를 사용할 수 있도록 변경
- Keywords 인덱스 설정 변경
- `ngram_tokenizer` 를 사용한 n-gram 인덱스 생성
- `nfc_normalizer` 를 사용한 자/모음 분리 및 초성 인덱스 생성
- 검색어 자동완성 시 초성검색이 가능해졌습니다.
- 검색어 자동완성 시 자/모음이 분리되어 검색되도록 변경되었습니다.
- AS-IS : `잡` 검색시 `자바` 조회X
- TO-BE : `잡` 검색시에도 `자바` 조회O
=> [DP-252] 한글 초성 검색, 자/모음 분리 검색 가능하도록 수정

src/docs/asciidoc/api/pick-commnet/pick-comment-modify.adoc, src/docs/asciidoc/api/pick-commnet/pick-comment-register.adoc, src/docs/asciidoc/api/pick-commnet/pick-comment.adoc, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickComment.java, src/main/java/com/dreamypatisiel/devdevdev/domain/exception/PickExceptionMessage.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickCommentRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/request/ModifyPickCommentRequest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickCommentControllerDocsTest.java
* 픽픽픽 댓글을 수정합니다.
* 회원 본인이 작성한 픽픽픽 수정 할 수 있습니다.
* 픽픽픽 공개 여부는 수정 할 수 없습니다.
* 삭제된 댓글을 수정 할 수 없습니다.
* 픽픽픽 댓글 작성 API request 에서 불필요한 pickOptionId가 제거되었습니다.
=> [DP-339] 픽픽픽 댓글 수정 API

src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/document/ElasticKeyword.java, src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticKeywordService.java, src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticKeywordServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/KeywordControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/KeywordControllerDocsTest.java
- [[PR - [DP-252] 한글 초성 검색, 자/모음 분리 검색 가능하도록 수정 #82]](https://github.com/dreamyPatisiel/devdevdev-server/pull/82) 의 내용만 cherry-pick 했습니다.
- 해당 commit 내용 기준으로 엘라스틱서치의 keyword 필드 타입이 변경되어 있습니다.
- sentry와 같이 main에서 바로 작업하는 경우가 있으므로 이부분 미리 반영이 필요할 것 같아 PR 올립니다.
- [엘라스틱서치 필드 타입 변경으로 인한 빌드 실패 사례(slack, 어제 발생)](https://dreamy-patisiel.slack.com/archives/C06CQGGVCLE/p1727276423651219?thread_ts=1727276015.778369&cid=C06CQGGVCLE)
- ElasticKeyword 도큐먼트 속성 변경
- 인덱스 설정 변경에 따른 필드 type 변경(completion → text)
- 필드명 변경(words → keyword)
- 검색 쿼리 변경
- multi_match 쿼리를 사용할 수 있도록 변경
- Keywords 인덱스 설정 변경
- `ngram_tokenizer` 를 사용한 n-gram 인덱스 생성
- `nfc_normalizer` 를 사용한 자/모음 분리 및 초성 인덱스 생성
- 검색어 자동완성 시 초성검색이 가능해졌습니다.
- 검색어 자동완성 시 자/모음이 분리되어 검색되도록 변경되었습니다.
- AS-IS : `잡` 검색시 `자바` 조회X
- TO-BE : `잡` 검색시에도 `자바` 조회O
=> [DP-252] 한글 초성 검색, 자/모음 분리 검색 가능하도록 수정 (cherry pick)

src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechArticleMainResponse.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechArticleMainResponseTest.java
- 기술블로그 메인 API or 북마크 목록 API 을 통해 기술블로그 목록을 조회할 때, 썸네일 이미지가 회사 로고로 대체되었는지 여부를 응답에 추가했습니다.
```
// 썸네일 이미지가 아티클 이미지라면 false, 회사 로고 이미지라면 true
"isLogoImage" : false, 
```
- Slack: https://dreamy-patisiel.slack.com/archives/C066AN5CS4X/p1725785519416209
=> [DP-373] 기술블로그 메인 조회시 썸네일 회사 로고 여부 isLogoImage 필드 추가

src/main/java/com/dreamypatisiel/devdevdev/LocalInitData.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Bookmark.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleService.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleController.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
- 기술블로그 북마크 요청시 status 값으로 오던 값을 제거하고, 서버에서 값을 확인하여 toggle 하는 방식으로 변경하였습니다.
- 전체적인 로직은 '픽픽픽/기술블로그 댓글 추천' 에서의 로직과 동일합니다.
=> [DP-374] 기술블로그 북마크 상태값 클라의존 제거

src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryCustom.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryImpl.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentControllerTest.java
-  pickOptionType 으로 filter 한 결과를 보여줘야 하기 때문에 count 쿼리 작성
- totalElements 를 검증하는 controller 테스트 코드 작성
- [관련 스레드](https://dreamy-patisiel.slack.com/archives/C066JK2U7P0/p1730966644472419?thread_ts=1730023094.202969&cid=C066JK2U7P0)
=> [DP-418] 픽픽픽 댓글/답글 총 갯수 계산식 변경

src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechCommentRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechCommentRepositoryCustom.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechCommentRepositoryImpl.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/MemberTechCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentCommonService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/web/dto/SliceCommentCustom.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
- 기술블로그 베스트댓글 조회 정책 변경
- 추천수 1개 이상일 경우에만 조회되도록 조건 추가
- 댓글 조회시 부모댓글개수 필드(totalOriginParentComments) 추가
- [관련 Slack](https://dreamy-patisiel.slack.com/archives/C076TT1ASNB/p1731221271199979?thread_ts=1730961402.999999&cid=C076TT1ASNB) 
- 카운트 쿼리가 잘 나가는지, 추천수 개수 조건절 확인 부탁드립니다!ㅎㅎ
=> [DP-420] 기술블로그 베스트댓글 조회 정책 변경(추천수 1개 이상, 부모댓글개수 필드 추가)

src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechCommentRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentCommonService.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
- `totalOriginParentComments` 삭제된 댓글은 카운트에서 제외되도록 수정
- [관련 Slack](https://dreamy-patisiel.slack.com/archives/C076TT1ASNB/p1731430481937249?thread_ts=1730961402.999999&cid=C076TT1ASNB)
=> [DP-420] fix(techComment): 삭제된 댓글은 부모 댓글 카운트 제외

src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Pick.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickServiceTest.java
- 픽픽픽 게시글/댓글 신고 기능이 추가됨에 따라, 일반회원이더라도 픽픽픽 작성시 승인 절차를 거치지 않고 바로 승인되도록 수정
- getDefaultContentStatusByMemberRole() 메서드를 우선 Deprecate 하긴 했는데, 완전히 제거해도 된다면 제거하는 것이 좋을 것 같기도 합니다!
=> [DP-452] fix: 일반회원 픽픽픽 작성시 자동 승인

src/main/java/com/dreamypatisiel/devdevdev/web/dto/util/TechArticleResponseUtils.java
- 기술블로그 상세를 조회할 때, GA값이 없어 익명회원이 null인 상태로 추천여부 조회시 생기는 NPE 방지
- [관련 슬랙](https://dreamy-patisiel.slack.com/archives/C066AN5CS4X/p1736079682237059)
=> [DP-447] fix: GA 값 없을 경우 대응

src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechArticleRecommend.java, src/main/java/com/dreamypatisiel/devdevdev/web/dto/util/TechArticleResponseUtils.java
- 기술블로그 상세 조회 시, 회원/익명회원의 해당 글 추천여부를 확인하는 로직이 있는데, 이때 각 추천 entity의 추천자(회원 or 익명회원)에 따라 필터링이 필요하여 이부분 적용했습니다.
=> [DP-464] bugfix: 회원/익명회원의 추천 여부 조회 메서드 -> 해당 추천의 추천자가 회원/익명회원인지 필터링하는 로직 추가

src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techArticle/GuestTechArticleService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techArticle/MemberTechArticleService.java, src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechArticleRecommendResponse.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
- 기술블로그 추천 API 응답에 총 추천수(recommendTotalCount) 추가
- [관련슬랙](https://dreamy-patisiel.slack.com/archives/C07KGP2106R/p1737039530068359)
=> fix: 기술블로그 추천 API 응답에 총 추천수 추가

src/main/java/com/dreamypatisiel/devdevdev/domain/repository/notification/NotificationRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationService.java, src/main/java/com/dreamypatisiel/devdevdev/test/TestController.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/notification/NotificationController.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationServiceTest.java
- 회원에 대해 생성된 알림 일괄 제거 API (개발용)
- [관련 스레드](https://dreamy-patisiel.slack.com/archives/C066AN5CS4X/p1746167540519839)
- 개발용이므로 문서를 따로 작성하진 않았습니다..!
=> feat(notification): 알림 일괄 삭제 API

src/main/java/com/dreamypatisiel/devdevdev/domain/repository/SseEmitterRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationService.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/notification/MockNotificationServiceTest.java
>
(확인 후 지워주세요)
- 기존 SSE 인스턴스가 있으면 해당 인스턴스 반환
- SSE 인스턴스가 없으면 새롭게 생성
- [관련 스레드](https://dreamy-patisiel.slack.com/archives/C0673T3JFJM/p1746441286283529)
- 재연결 시 SSE를 새롭게 생성해서 발생하는 문제라고 생각해서 👆위처럼 코드 작성 했습니다.
=> [DP-518] SSE 하트비트 간헐적으로 안오는 이슈

src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/subscription/SubscriableCompanyResponse.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/subscription/SubscriptionControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/SubscriptionControllerDocsTest.java
- 구독 가능한 기업 목록 (GET /subscriptions/companies) 응답값에 기업명을 추가했습니다.
- [관련스레드](https://dreamy-patisiel.slack.com/archives/C066AN5CS4X/p1746759231745469)
=> [DP-520] fix: 구독 가능한 기업 목록 - 기업명 추가

src/docs/asciidoc/api/mypage/change-nickname.adoc, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java, src/main/java/com/dreamypatisiel/devdevdev/domain/exception/NicknameExceptionMessage.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/exception/ApiControllerAdvice.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/member/MypageController.java, src/main/java/com/dreamypatisiel/devdevdev/web/dto/request/member/ChangeNicknameRequest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/entity/MemberTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/member/MyPageControllerUsedMockServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsUsedMockServiceTest.java
- 회원은 닉네임을 변경할 수 있다.
- 익명 회원은 닉네임 변경을 할 수 없다. (401)
X
- 자유 닉네임 설정 가능성을 고려해 "A B C" 형식 유효성 검사는 생략했는데, 지금 단계에서는 넣는 게 좋을까요?
=> [DP-535] 닉네임 변경 API

src/docs/asciidoc/api/pick-commnet/pick-comment-reply-register.adoc, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceV2.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/dto/PickCommentDto.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickController.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceV2Test.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickTestUtils.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickCommentControllerDocsTest.java
>
(확인 후 지워주세요)
- [레포 이름 #이슈번호](이슈 주소)
>
=> [DP-525] 익명회원 픽픽픽 답글 작성

src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/member/MypageController.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/member/MyPageControllerUsedMockServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsUsedMockServiceTest.java
- 닉네임 변경 API 응답값에 변경된 닉네임 문자열 추가
- https://dreamy-patisiel.slack.com/archives/C0673T3JFJM/p1752071043713299
=> [DP-535] 닉네임 변경 API 응답 변경(변경된 닉네임 문자열 추가)

src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java, src/main/java/com/dreamypatisiel/devdevdev/domain/policy/NicknameChangePolicy.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java, src/test/java/com/dreamypatisiel/devdevdev/domain/entity/MemberTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java
- 사연: https://dreamy-patisiel.slack.com/archives/C066AN5CS4X/p1752991340960229
- 닉네임 변경 가능 시간 환경변수화(없으면 기본값 24시간, dev 환경변수만 추가하면 됨)
```yml
nickname:
change:
interval:
hours: 0
```
환경변수화, 코드로 분기, DB로 관리하는 것 중 환경변수로 둔 이유는 다음과 같습니다!
1. 코드로 분기 - 개발환경을 위한 정책 분기가 코드로 관리되는 것이 적절하지 않다고 판단
2. DB로 관리 - 다소 오버엔지니어링, 개발환경에 다른 정책분리 수요가 많아지면 고려해볼만함, 계속해서 DB를 조회해야하거나, 인메모리로 올려서 캐싱하더라도 캐시를 날리고 새로 업데이트하는 기능을 달지 않으면 장점이 없어보임
3. 환경변수화 - 가장 간편하게 분리 및 수정 배포 가능
=> fix(nickname): 회원 닉네임 변경 가능 시간 환경변수화

src/docs/asciidoc/api/tech-article-comment/tech-article-comment-register.adoc, src/docs/asciidoc/api/tech-article-comment/tech-article-reply-register.adoc, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechComment.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleServiceStrategy.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/dto/TechCommentDto.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentServiceV2.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/MemberTechCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentCommonService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentController.java, src/main/resources/application-local.yml, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentServiceV2Test.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
>
(확인 후 지워주세요)
- [레포 이름 #이슈번호](이슈 주소)
>
=> [DP-529] 익명회원 기술블로그 답글 작성

src/docs/asciidoc/api/tech-article-comment/tech-article-comment-modify.adoc, src/docs/asciidoc/api/tech-article-comment/tech-article-reply-register.adoc, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechComment.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechCommentRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/dto/TechCommentDto.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentServiceV2.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/MemberTechCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentCommonService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentController.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentServiceV2Test.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
>
(확인 후 지워주세요)
- [레포 이름 #이슈번호](이슈 주소)
>
=> [DP-531] 익명회원 기술블로그 댓글/답글 삭제

src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechKeyword.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechKeywordRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechKeywordRepositoryCustom.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechKeywordRepositoryImpl.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/keyword/TechKeywordService.java, src/main/java/com/dreamypatisiel/devdevdev/global/config/CustomMySQLFunctionContributor.java, src/main/java/com/dreamypatisiel/devdevdev/global/utils/HangulUtils.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/KeywordController.java, src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechKeywordServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticKeywordServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/global/utils/HangulUtilsTest.java, src/test/java/com/dreamypatisiel/devdevdev/test/MySQLTestContainer.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/KeywordControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/KeywordControllerDocsTest.java
- 검색어 자동완성 기능 구현
- 초성검색, 자/모음 분리 검색 가능
- 한글 관련 함수 호출을 위한 HangulUtils 생성
- MATCH AGAINST 함수 사용을 위하여 FunctionContributor 등록
- tech_keyword 테이블 생성 및 인덱스 생성
- MySQL 테스트컨테이너 등록
- 검색어 데이터 삽입시 인덱스가 생성되려면 @BeforeTransaction 을 통해 넣어주어야 해서 그렇게 구현했습니다! (https://rkrkrr0101.tistory.com/114) 이렇게 안 하면 조회결과가 0이더라구요ㅠㅠ
=> [DP-554] 검색어 자동완성 API (ES → MySQL 마이그레이션)
