src/main/java/com/dreamypatisiel/devdevdev/global/utils/CookieUtils.java
=> feat(시큐리티): OAuth2.0 + JWT

src/main/java/com/dreamypatisiel/devdevdev/global/constant/SecurityConstant.java, src/main/java/com/dreamypatisiel/devdevdev/global/security/config/SecurityConfig.java, src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/handler/JwtAuthenticationEntryPointHandler.java, src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/model/JwtCookieConstant.java, src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/model/TokenExpireTime.java, src/main/java/com/dreamypatisiel/devdevdev/global/security/oauth2/handler/OAuth2AuthenticationFailureHandler.java, src/main/java/com/dreamypatisiel/devdevdev/global/utils/CookieUtils.java, src/test/java/com/dreamypatisiel/devdevdev/global/security/oauth2/handler/OAuth2SuccessHandlerTest.java, src/test/java/com/dreamypatisiel/devdevdev/global/utils/CookieUtilsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/TokenControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TokenControllerDocsTest.java
=> 로그인 활성 상태 쿠키 추가

src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Pick.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickBlame.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickBlameType.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickComment.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickCommentReplyRecommend.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickOption.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickOptionImage.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickReply.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickVote.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/PickContents.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/Title.java, src/test/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/PickContentsTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/TitleTest.java
* 테이블 이름 변경
* 컬럼 및 추가 삭제
* 테이블 구조 변경
* pick_option 테이블 추가
=> [DP-99] 픽픽픽 엔티티 수정

src/test/java/com/dreamypatisiel/devdevdev/web/controller/TokenControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TokenControllerDocsTest.java
- PR 피드백 반영
- 테스트 코드, RestDocs 작성
=> [DP-97] feat: 테스트 토큰 생성 API

src/docs/asciidoc/api/token-test/token-test-admin.adoc, src/docs/asciidoc/api/token-test/token-test-user.adoc, src/main/resources/static/docs/index.html, src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet, src/test/resources/org/springframework/restdocs/templates/request-cookies.snippet, src/test/resources/org/springframework/restdocs/templates/request-fields.snippet, src/test/resources/org/springframework/restdocs/templates/request-headers.snippet, src/test/resources/org/springframework/restdocs/templates/response-cookies.snippet, src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
=> [DP-118] Rest Docs 오류 수정

src/main/java/com/dreamypatisiel/devdevdev/DevdevdevApplication.java, src/main/java/com/dreamypatisiel/devdevdev/LocalInitData.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Pick.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/Count.java, src/main/java/com/dreamypatisiel/devdevdev/domain/policy/PickPopularScorePolicy.java, src/main/java/com/dreamypatisiel/devdevdev/domain/policy/PopularScorePolicy.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickRepositoryCustom.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickRepositoryImpl.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickSort.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PicksResponse.java, src/main/java/com/dreamypatisiel/devdevdev/global/utils/BigDecimalUtils.java, src/main/resources/static/docs/index.html, src/test/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/CountTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/policy/PickPopularScorePolicyTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickRepositoryTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/GuestPickServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/MemberPickServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/global/utils/BigDecimalUtilsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/PickControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickControllerDocsTest.java
=> [DP-132] PickRepositoryImpl 쿼리 수정

src/main/java/com/dreamypatisiel/devdevdev/web/controller/TokenController.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/TokenControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TokenControllerDocsTest.java
- 멱등성을 고려하여 리프레시 GET에서 POST로 변경
=> [DP-146] HTTP 메소드 변경

src/docs/asciidoc/api/token-refresh/token-refresh.adoc
=> [DP-113] 리프레시 REST DOCS 수정

.github/workflows/cicd-ec2.yml, .github/workflows/cicd-gcp.yml
`./gradlew build test` -> `./gradlew build bootjar`
=> [DP-149] 빌드시 test → bootjar로 빌드되도록 수정

src/docs/asciidoc/api/common/common.adoc, src/docs/asciidoc/index.adoc, src/main/java/com/dreamypatisiel/devdevdev/global/security/filter/SecurityExceptionFilter.java, src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/handler/JwtAuthenticationEntryPointHandler.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/LogoutController.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/exception/ApiControllerAdvice.java, src/main/java/com/dreamypatisiel/devdevdev/web/response/BasicResponse.java, src/main/resources/static/docs/index.html, src/test/java/com/dreamypatisiel/devdevdev/web/controller/LogoutControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/TokenControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/JwtExceptionDocsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/SupportControllerDocsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TokenControllerDocsTest.java
* 토큰 예외 REST DOCS 추가
* 인증에 관련된 토큰 예외 401로 변경
=> [DP-148] 토큰 예외 REST DOCS 추가

.github/workflows/cicd-gcp.yml, build.gradle
=> fix(tech): java 버전 17 -> 21 변경

Dockerfile, src/main/resources/static/docs/index.html
- Dockerfile java 버전 수정
ㅠㅠ 죄송해요 세웅님,,,,,
=> fix(tech): java 버전 17 -> 21 변경(Dockerfile 수정)

.github/workflows/cicd-gcp.yml
* test 코드에 application-storage-s3.yml 설정 미스
* actions secret respository 네이밍 실수
* 기존: APPICATION_STORAGE_S3
* 변경: APPLICATION_STORAGE_S3
=> [DP-113] CI/CD 문제

.github/workflows/build.yml, .github/workflows/cicd-ec2.yml
- 기존의 github workflow 빌드 방식은 빌드환경에서의 test & build 성공 여부를 merge 후에 확인할 수 있으므로, 빌드시 발생하는 에러를 추가 PR로 대응할 수밖에 없음
- 하나의 PR 내에서 커밋이 발생할 때마다 workflow를 통해 test & build 성공 여부를 확인한 후, merge했을 때에는 배포까지 진행하도록 workflow 추가
=> [DP-158] PR 생성 및 커밋시 빌드 테스트 worflow 추가

.github/workflows/build.yml, src/docs/asciidoc/api/tech-article/main.adoc, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechArticleSort.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/TechArticleResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleService.java, src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleService.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/PickController.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleController.java, src/main/resources/static/docs/index.html, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleServiceStrategyTest.java, src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticsearchSupportTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/format/ApiDocsFormatGenerator.java
- 메인 API와 통합 및 검색어 유무로 분기 처리
- TechArticleSort에 '정확도순' 추가
- 정확도순을 통한 페이지네이션 시 score(점수) 누락시 예외처리
- 검색 테스트코드 작성(단순 조회, 다음페이지 조회)
=> [DP-59] 기술블로그 검색 API

.gitignore, build.gradle, src/main/resources/static/docs/index.html
- index.html gitignore 추가
- mariadb 의존성 추가
=> [DP-155] 놓친 부분 추가 PR

src/main/resources/static/docs/index.html
=> [DP-155] REST DOCS 실수..

src/docs/asciidoc/api/common/common.adoc, src/docs/asciidoc/api/pick/pick-detail.adoc, src/docs/asciidoc/api/pick/pick-vote.adoc, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/AnonymousMember.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Pick.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickOption.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickVote.java, src/main/java/com/dreamypatisiel/devdevdev/domain/exception/PickExceptionMessage.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/AnonymousMemberRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickVoteRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/dto/VotePickOptionDto.java, src/main/java/com/dreamypatisiel/devdevdev/global/utils/CookieUtils.java, src/main/java/com/dreamypatisiel/devdevdev/web/WebConstant.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/PickController.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/request/VotePickOptionRequest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/CorsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/PickControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickControllerDocsTest.java
* 익명 회원 픽픽픽 투표 기능 추가
* 픽픽픽 작성 시 회원의 권한에 따라서 픽픽픽 상태 변경
* 일반 회원 -> READY
* 어드민 회원 -> APPROVAL
* 픽픽픽 상세 조회, 픽픽픽 메인 조회 익명 회원 로직 적용
* 픽픽픽 투표 여부, 픽픽픽 옵션 투표 여부
=> [DP-117] 익명 회원 픽픽픽 투표

src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickVote.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/MyPickMainOptionResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/MyPickMainResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PickDetailOptionImage.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PickDetailOptionImageResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PickDetailOptionResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PickDetailResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PickMainOptionResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PickMainResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/util/PickResponseUtils.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/response/util/PickResponseUtilsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/PickControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickControllerDocsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
* 픽픽픽 상세 isVoted 추가
* 픽픽픽 상세 userId 마스킹 처리
* 픽픽픽 응답 Utils 생성
=> [DP-208] 픽픽픽 응답 수정

src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickOptionRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickRepositoryImpl.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/VotePickOptionResponse.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickServiceTest.java
* 픽픽픽 메인 쿼리 수정
* pickVote를 조인 제거
* 투표를 하게 되면 picVote를 함께 조인하기 때문에 픽픽픽 메인 조회에 영향을 미침
* 픽픽픽 투표 수정
* 픽픽픽 옵션에 투표한 이력이 있는 경우
* 동일한 픽픽픽 옵션에 투표한 경우 예외발생
* 다른 픽픽픽 옵션에 투표했을 경우
* 투표를 하고 싶은 픽픽픽 옵션은 투표수 증가, 기존 픽픽픽 옵션 투표는 삭제 및 투표수 증가
* 픽픽픽 옵션에 투표한 이력이 없는 경우
* 투표를 하고 싶은 픽픽픽 옵션 투표수 증가
=> [DP-216] 픽픽픽 메인 쿼리, 픽픽픽 투표 API 수정

.github/workflows/cicd-ec2-prod.yml
=> fix(cicd): cicd-ec2-prod.yml 파일 수정

src/docs/asciidoc/api/tech-article-comment/tech-article-comment.adoc, src/docs/asciidoc/api/tech-article-comment/tech-article-reply-register.adoc, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechComment.java, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechReply.java, src/main/java/com/dreamypatisiel/devdevdev/domain/exception/TechArticleExceptionMessage.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechCommentRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechReplyRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/TechCommentResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/TechReplyResponse.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentController.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/request/RegisterTechReplyRequest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
* 회원은 기술블로그 댓글에 답글을 작성할 수 있습니다.
* 존재하지 않거나 삭제된 댓글에 답글을 작성하면 예외가 발생합니다.
=> [DP-295] 기술블로그 답글 작성 API

src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleService.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticsearchSupportTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
- 데이터 생성시 random으로 들어가는 날짜값을 정해진 값으로 들어가도록 수정했습니다.
- 정렬값 검증 후 반환되는 값을 새로운 변수에 재할당하여 사용하도록 수정했습니다.
=> [DP-333] 엘라스틱서치 테스트코드 데이터 수리

src/main/java/com/dreamypatisiel/devdevdev/aop/TransactionalCheckAspect.java, src/main/java/com/dreamypatisiel/devdevdev/aop/WriteOperationContext.java, src/main/java/com/dreamypatisiel/devdevdev/aop/WriteOperationDetectorAspect.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java, src/main/java/com/dreamypatisiel/devdevdev/eventlistener/HibernateEventListenerConfig.java, src/main/java/com/dreamypatisiel/devdevdev/eventlistener/WriteQueryEventListener.java
=> [DP-383] @Transactional 누락 방지

src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentController.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleController.java
- api endpoint 공통path 수정
- 머지 및 빌드 관련 히스토리 [Slack 스레드](https://dreamy-patisiel.slack.com/archives/C066AN5CS4X/p1729411059128939)
=> [DP-394] 빌드를 위한 PR

src/docs/asciidoc/api/tech-article-comment/tech-article-comment-recommend.adoc, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryCustom.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryImpl.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
- [픽픽픽 댓글/조회 관련 스레드](https://dreamy-patisiel.slack.com/archives/C066JK2U7P0/p1730100262538799?thread_ts=1730023094.202969&cid=C066JK2U7P0)
- [기술블로그 베스트 댓글 관련 스레드](https://dreamy-patisiel.slack.com/archives/C066AN5CS4X/p1730428277267989)
=> [DP-412] 픽픽픽 댓글/답글 조회 체크박스 정책 수정 대응

src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java
- [관련 스레드](https://dreamy-patisiel.slack.com/archives/C066JK2U7P0/p1730966644472419?thread_ts=1730023094.202969&cid=C066JK2U7P0)
>
=> [DP-418] 픽픽픽 댓글/답글 총 갯수 계산식 변경

src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/model/JwtCookieConstant.java, src/main/java/com/dreamypatisiel/devdevdev/global/utils/CookieUtils.java, src/test/java/com/dreamypatisiel/devdevdev/global/security/oauth2/handler/OAuth2SuccessHandlerTest.java, src/test/java/com/dreamypatisiel/devdevdev/global/utils/CookieUtilsTest.java
=> feat: 로그인유저 isAdmin 쿠키로 응답

.github/workflows/cicd-ec2-dev.yml, .github/workflows/cicd-ec2-prod.yml
- rm 파일 없더라도 에러 무시하도록 -f 추가
- Dockerfile dev/prod 바뀐거 수정
=> [DP-495] dev cicd 연결(2)

build.gradle, src/docs/asciidoc/api/notification/notification.adoc, src/docs/asciidoc/api/notification/read-notification.adoc, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Notification.java, src/main/java/com/dreamypatisiel/devdevdev/domain/exception/NotificationExceptionMessage.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/notification/NotificationRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationService.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/notification/NotificationController.java, src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/notification/NotificationReadResponse.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/notification/NotificationControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/NotificationControllerDocsTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
- 회원은 단건 알림 읽기를 할 수 있다.
- 비회원이 단건 알림 읽기를 요청하면 예외가 발생한다.
=> [DP-504] 알림 단건 읽기 API 

src/docs/asciidoc/api/notification/notifications.adoc, src/main/java/com/dreamypatisiel/devdevdev/DevdevdevApplication.java, src/main/java/com/dreamypatisiel/devdevdev/domain/repository/SseEmitterRepository.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationService.java, src/main/java/com/dreamypatisiel/devdevdev/global/config/AsyncConfig.java, src/main/java/com/dreamypatisiel/devdevdev/scheduler/AsyncHeartbeatSender.java, src/main/java/com/dreamypatisiel/devdevdev/scheduler/SseEmitterHeartbeatScheduler.java, src/test/java/com/dreamypatisiel/devdevdev/scheduler/AsyncHeartbeatSenderTest.java, src/test/java/com/dreamypatisiel/devdevdev/scheduler/SseEmitterHeartbeatSchedulerTest.java
>
(확인 후 지워주세요)
- `@Scheduled`는 기본적으로 싱글 스레드인데, 비동기(`@Async`)를 붙이면, Spring이 별도 스레드풀에서 해당 작업을 실행
- heartbeat 를 사용해서 계속 커넥션을 유지해야하기 때문에 비동기(`@Async`) 방식을 사용함
- 기대 효과
- 빠른 응답
- 스케줄러 thread block 방지
- 전체 시스템 안정성 유지
- [관련 스레드](https://dreamy-patisiel.slack.com/archives/C07395PS007/p1745806844369299?thread_ts=1745734413.731289&cid=C07395PS007)
> 주석을 최대한 작성했습니다.
=> [DP-515] sse heartbeat 스케줄러 개발

src/docs/asciidoc/api/tech-article-comment/tech-article-comment-register.adoc, src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechComment.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleServiceStrategy.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/dto/TechCommentDto.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentServiceV2.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/MemberTechCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentCommonService.java, src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentService.java, src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentController.java, src/main/resources/application-local.yml, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java, src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentServiceV2Test.java, src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java, src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
>
(확인 후 지워주세요)
- [레포 이름 #이슈번호](이슈 주소)
>
=> [DP-528] 익명회원 기술블로그 댓글 작성
